{"created": 1755594376.624713, "duration": 174.59331727027893, "exitcode": 1, "root": "C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Bay", "environment": {}, "summary": {"failed": 4, "total": 4, "collected": 4}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/test_Bay_order_approval.py", "type": "Module"}]}, {"nodeid": "tests/test_Bay_order_approval.py", "outcome": "passed", "result": [{"nodeid": "tests/test_Bay_order_approval.py::test_approve_order", "type": "Function", "lineno": 18}, {"nodeid": "tests/test_Bay_order_approval.py::test_approve_bulk_order", "type": "Function", "lineno": 97}, {"nodeid": "tests/test_Bay_order_approval.py::test_reject_order", "type": "Function", "lineno": 141}, {"nodeid": "tests/test_Bay_order_approval.py::test_reject_bulk_order", "type": "Function", "lineno": 230}]}], "tests": [{"nodeid": "tests/test_Bay_order_approval.py::test_approve_order", "lineno": 18, "outcome": "failed", "keywords": ["test_approve_order", "test_Bay_order_approval.py", "tests", "Bay", ""], "setup": {"duration": 0.7423423000000184, "outcome": "passed"}, "call": {"duration": 43.21134019999954, "outcome": "failed", "crash": {"path": "C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nCall log:\n  - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\uc790\ub3d9\ud654\uac1c\ubcc4\uc81c\ud488_1\")).first.locator(\"td:nth-child(2)\")"}, "traceback": [{"path": "tests\\test_Bay_order_approval.py", "lineno": 24, "message": ""}, {"path": "helpers\\approve_utils.py", "lineno": 136, "message": "in check_approval_status_buttons"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py", "lineno": 16878, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py", "lineno": 444, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py", "lineno": 618, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 61, "message": "in send"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "TimeoutError"}], "longrepr": "page = <Page url='https://stg.bay.centurion.ai.kr/orders/approve-request?product-name=%25EC%259E%2590%25EB%258F%2599%25ED%259...%259C%25EB%25B3%2584%25EC%25A0%259C%25ED%2592%2588_1&start-date=2025-08-19&end-date=2025-08-19&status=APPROVED&page=1'>\n\n    def test_approve_order(page:Page):\n        bay_login(page, account=\"qaje\") #\ub85c\uadf8\uc778\ud560 \uacc4\uc815\n        page.goto(URLS[\"bay_approval\"])\n        page.wait_for_timeout(2000)\n    \n>       check_approval_status_buttons(page, \"\uc2b9\uc778 \ub300\uae30\", products[0], order_rule[0], bulk=False, approve=True)\n\ntests\\test_Bay_order_approval.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nhelpers\\approve_utils.py:136: in check_approval_status_buttons\n    product_text = product_cell.inner_text().strip()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:16878: in inner_text\n    self._sync(self._impl_obj.inner_text(timeout=timeout))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py:444: in inner_text\n    return await self._frame.inner_text(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:618: in inner_text\n    return await self._channel.send(\"innerText\", locals_to_params(locals()))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000002211C55FE00>\ncb = <function Channel.send.<locals>.<lambda> at 0x000002211C663560>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nE           Call log:\nE             - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\uc790\ub3d9\ud654\uac1c\ubcc4\uc81c\ud488_1\")).first.locator(\"td:nth-child(2)\")\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "teardown": {"duration": 0.0326922000022023, "outcome": "passed"}}, {"nodeid": "tests/test_Bay_order_approval.py::test_approve_bulk_order", "lineno": 97, "outcome": "failed", "keywords": ["test_approve_bulk_order", "test_Bay_order_approval.py", "tests", "Bay", ""], "setup": {"duration": 0.07302879999770084, "outcome": "passed"}, "call": {"duration": 43.24706200000219, "outcome": "failed", "crash": {"path": "C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nCall log:\n  - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\uc790\ub3d9\ud654\uc81c\ud488_1\")).first.locator(\"td:nth-child(2)\")"}, "traceback": [{"path": "tests\\test_Bay_order_approval.py", "lineno": 103, "message": ""}, {"path": "helpers\\approve_utils.py", "lineno": 136, "message": "in check_approval_status_buttons"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py", "lineno": 16878, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py", "lineno": 444, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py", "lineno": 618, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 61, "message": "in send"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "TimeoutError"}], "longrepr": "page = <Page url='https://stg.bay.centurion.ai.kr/orders/approve-request?product-name=%25EC%259E%2590%25EB%258F%2599%25ED%2599%2594%25EC%25A0%259C%25ED%2592%2588_1&start-date=2025-08-19&end-date=2025-08-19&status=APPROVED&page=1'>\n\n    def test_approve_bulk_order(page:Page):\n        bay_login(page, account=\"qaje\")\n        page.goto(URLS[\"bay_approval\"])\n        page.wait_for_timeout(2000)\n    \n>       check_approval_status_buttons(page, \"\uc2b9\uc778 \ub300\uae30\", bulk_products[0], order_rule[1], bulk=True, approve=True)\n\ntests\\test_Bay_order_approval.py:103: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nhelpers\\approve_utils.py:136: in check_approval_status_buttons\n    product_text = product_cell.inner_text().strip()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:16878: in inner_text\n    self._sync(self._impl_obj.inner_text(timeout=timeout))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py:444: in inner_text\n    return await self._frame.inner_text(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:618: in inner_text\n    return await self._channel.send(\"innerText\", locals_to_params(locals()))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000002211C55FE00>\ncb = <function Channel.send.<locals>.<lambda> at 0x000002211C5F9F80>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nE           Call log:\nE             - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\uc790\ub3d9\ud654\uc81c\ud488_1\")).first.locator(\"td:nth-child(2)\")\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "teardown": {"duration": 0.021824700001161546, "outcome": "passed"}}, {"nodeid": "tests/test_Bay_order_approval.py::test_reject_order", "lineno": 141, "outcome": "failed", "keywords": ["test_reject_order", "test_Bay_order_approval.py", "tests", "Bay", ""], "setup": {"duration": 0.08669069999814383, "outcome": "passed"}, "call": {"duration": 43.15461270000014, "outcome": "failed", "crash": {"path": "C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nCall log:\n  - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\ubc1c\uc8fc \uac70\uc808 \uc81c\ud488_3\")).first.locator(\"td:nth-child(2)\")"}, "traceback": [{"path": "tests\\test_Bay_order_approval.py", "lineno": 147, "message": ""}, {"path": "helpers\\approve_utils.py", "lineno": 136, "message": "in check_approval_status_buttons"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py", "lineno": 16878, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py", "lineno": 444, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py", "lineno": 618, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 61, "message": "in send"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "TimeoutError"}], "longrepr": "page = <Page url='https://stg.bay.centurion.ai.kr/orders/approve-request?product-name=%25EB%25B0%259C%25EC%25A3%25BC%2520%25E...%25EC%25A0%2588%2520%25EC%25A0%259C%25ED%2592%2588_3&start-date=2025-08-19&end-date=2025-08-19&status=APPROVED&page=1'>\n\n    def test_reject_order(page:Page):\n        bay_login(page, account=\"qaje\")\n        page.goto(URLS[\"bay_approval\"])\n        page.wait_for_timeout(2000)\n    \n>       check_approval_status_buttons(page, \"\uc2b9\uc778 \ub300\uae30\", reject_products[2], order_rule[0], bulk=False, approve=True)\n\ntests\\test_Bay_order_approval.py:147: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nhelpers\\approve_utils.py:136: in check_approval_status_buttons\n    product_text = product_cell.inner_text().strip()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:16878: in inner_text\n    self._sync(self._impl_obj.inner_text(timeout=timeout))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py:444: in inner_text\n    return await self._frame.inner_text(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:618: in inner_text\n    return await self._channel.send(\"innerText\", locals_to_params(locals()))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000002211C55FE00>\ncb = <function Channel.send.<locals>.<lambda> at 0x000002211C9EBEC0>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nE           Call log:\nE             - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\ubc1c\uc8fc \uac70\uc808 \uc81c\ud488_3\")).first.locator(\"td:nth-child(2)\")\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "teardown": {"duration": 0.016869000002770917, "outcome": "passed"}}, {"nodeid": "tests/test_Bay_order_approval.py::test_reject_bulk_order", "lineno": 230, "outcome": "failed", "keywords": ["test_reject_bulk_order", "test_Bay_order_approval.py", "tests", "Bay", ""], "setup": {"duration": 0.06856110000080662, "outcome": "passed"}, "call": {"duration": 43.0611306000028, "outcome": "failed", "crash": {"path": "C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nCall log:\n  - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\ubc1c\uc8fc \uac70\uc808 \uc81c\ud488_1\")).first.locator(\"td:nth-child(2)\")"}, "traceback": [{"path": "tests\\test_Bay_order_approval.py", "lineno": 235, "message": ""}, {"path": "helpers\\approve_utils.py", "lineno": 136, "message": "in check_approval_status_buttons"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py", "lineno": 16878, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py", "lineno": 444, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py", "lineno": 618, "message": "in inner_text"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 61, "message": "in send"}, {"path": "..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py", "lineno": 528, "message": "TimeoutError"}], "longrepr": "page = <Page url='https://stg.bay.centurion.ai.kr/orders/approve-request?product-name=%25EB%25B0%259C%25EC%25A3%25BC%2520%25E...%25EC%25A0%2588%2520%25EC%25A0%259C%25ED%2592%2588_1&start-date=2025-08-19&end-date=2025-08-19&status=APPROVED&page=1'>\n\n    def test_reject_bulk_order(page:Page):\n        bay_login(page, account=\"qaje\")\n        page.goto(URLS[\"bay_approval\"])\n        page.wait_for_timeout(2000)\n>       check_approval_status_buttons(page, \"\uc2b9\uc778 \ub300\uae30\", reject_products[0], order_rule[1], bulk=False, approve=True)\n\ntests\\test_Bay_order_approval.py:235: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nhelpers\\approve_utils.py:136: in check_approval_status_buttons\n    product_text = product_cell.inner_text().strip()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:16878: in inner_text\n    self._sync(self._impl_obj.inner_text(timeout=timeout))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_locator.py:444: in inner_text\n    return await self._frame.inner_text(\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:618: in inner_text\n    return await self._channel.send(\"innerText\", locals_to_params(locals()))\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000002211C55FE00>\ncb = <function Channel.send.<locals>.<lambda> at 0x000002211CA97CE0>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.\nE           Call log:\nE             - waiting for locator(\"table tbody tr\").filter(has=locator(\"td:nth-child(2)\").filter(has_text=\"\ubc1c\uc8fc \uac70\uc808 \uc81c\ud488_1\")).first.locator(\"td:nth-child(2)\")\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "teardown": {"duration": 0.10687189999953262, "outcome": "passed"}}]}