{"created": 1751275085.1343844, "duration": 2.045830488204956, "exitcode": 1, "root": "C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Bay", "environment": {}, "summary": {"failed": 1, "total": 1, "collected": 1}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/test_Bay_order_status_fail.py", "type": "Module"}]}, {"nodeid": "tests/test_Bay_order_status_fail.py", "outcome": "passed", "result": [{"nodeid": "tests/test_Bay_order_status_fail.py::test_order_status_fail", "type": "Function", "lineno": 12}]}], "tests": [{"nodeid": "tests/test_Bay_order_status_fail.py::test_order_status_fail", "lineno": 12, "outcome": "failed", "keywords": ["test_order_status_fail", "test_Bay_order_status_fail.py", "tests", "Bay", ""], "setup": {"duration": 1.1720006000250578, "outcome": "passed"}, "call": {"duration": 0.0013352999230846763, "outcome": "failed", "crash": {"path": "C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\Bay\\tests\\test_Bay_order_status_fail.py", "lineno": 21, "message": "ValueError: [FAIL] '\ubc1c\uc8fc \uc2e4\ud328' \uc0c1\ud0dc\uc758 \uc81c\ud488\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."}, "traceback": [{"path": "tests\\test_Bay_order_status_fail.py", "lineno": 21, "message": "ValueError"}], "stdout": "\u274c Error in test_order_status_fail: [FAIL] '\ubc1c\uc8fc \uc2e4\ud328' \uc0c1\ud0dc\uc758 \uc81c\ud488\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\n", "longrepr": "page = <Page url='about:blank'>\n\n    def test_order_status_fail(page: Page):\n        status_name = \"\ubc1c\uc8fc \uc2e4\ud328\"\n        expected = order_status_map[status_name]\n    \n        try:\n            # delivery_status == 6\uc778 \uc81c\ud488 \ubaa9\ub85d \ud544\ud130\ub9c1\n            filtered_products = filter_products_by_delivery_status(6)\n            if not filtered_products:\n>               raise ValueError(f\"[FAIL] '{status_name}' \uc0c1\ud0dc\uc758 \uc81c\ud488\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\")\nE               ValueError: [FAIL] '\ubc1c\uc8fc \uc2e4\ud328' \uc0c1\ud0dc\uc758 \uc81c\ud488\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\n\ntests\\test_Bay_order_status_fail.py:21: ValueError"}, "teardown": {"duration": 0.8375663999468088, "outcome": "passed"}}]}